services:
  favorite_literature_users_database:
    container_name: users_db
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: "fav_lit_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "6000:5432"